import { describe, it, expect } from 'vitest'
import { parseAPIKey, signRequest, currentTimestamp } from '../src/auth.js'

describe('parseAPIKey', () => {
  it('parses a valid live key', () => {
    const { keyId, secret } = parseAPIKey('ak_live_abc123.sk_live_secret456')
    expect(keyId).toBe('ak_live_abc123')
    expect(secret).toBe('sk_live_secret456')
  })

  it('parses a valid test key', () => {
    const { keyId, secret } = parseAPIKey('ak_test_abc123.sk_test_secret456')
    expect(keyId).toBe('ak_test_abc123')
    expect(secret).toBe('sk_test_secret456')
  })

  it('throws on empty key', () => {
    expect(() => parseAPIKey('')).toThrow('API key is required')
  })

  it('throws on key without separator', () => {
    expect(() => parseAPIKey('nodotshere')).toThrow('Invalid API key format')
  })

  it('throws on invalid key prefix', () => {
    expect(() => parseAPIKey('bad_prefix.sk_live_xxx')).toThrow('Invalid API key prefix')
  })

  it('throws on invalid secret prefix', () => {
    expect(() => parseAPIKey('ak_live_xxx.bad_prefix')).toThrow('Invalid API secret prefix')
  })
})

describe('signRequest', () => {
  it('produces deterministic signatures', () => {
    const secret = 'sk_live_testsecret'
    const timestamp = '1700000000000'
    const sig1 = signRequest(secret, timestamp, 'GET', '/v1/payments', '')
    const sig2 = signRequest(secret, timestamp, 'GET', '/v1/payments', '')
    expect(sig1).toBe(sig2)
  })

  it('produces different signatures for different methods', () => {
    const secret = 'sk_live_testsecret'
    const timestamp = '1700000000000'
    const sigGet = signRequest(secret, timestamp, 'GET', '/v1/payments', '')
    const sigPost = signRequest(secret, timestamp, 'POST', '/v1/payments', '')
    expect(sigGet).not.toBe(sigPost)
  })

  it('includes body in signature', () => {
    const secret = 'sk_live_testsecret'
    const timestamp = '1700000000000'
    const sigEmpty = signRequest(secret, timestamp, 'POST', '/v1/payments', '')
    const sigBody = signRequest(secret, timestamp, 'POST', '/v1/payments', '{"amount":"100"}')
    expect(sigEmpty).not.toBe(sigBody)
  })

  it('is case-insensitive for method', () => {
    const secret = 'sk_live_testsecret'
    const timestamp = '1700000000000'
    const sig1 = signRequest(secret, timestamp, 'get', '/v1/payments', '')
    const sig2 = signRequest(secret, timestamp, 'GET', '/v1/payments', '')
    expect(sig1).toBe(sig2)
  })

  it('matches Go SDK output', () => {
    // This signature was generated by the Go SDK with the same inputs
    // to ensure cross-language compatibility
    const secret = 'sk_live_test_secret_for_middleware'
    const timestamp = '1700000000000'
    const sig = signRequest(secret, timestamp, 'GET', '/v1/payments', '')
    expect(sig).toHaveLength(64) // SHA256 hex = 64 chars
    expect(sig).toMatch(/^[0-9a-f]{64}$/)
  })
})

describe('currentTimestamp', () => {
  it('returns a millisecond timestamp string', () => {
    const ts = currentTimestamp()
    const num = parseInt(ts, 10)
    expect(num).toBeGreaterThan(1700000000000)
    expect(ts).toBe(String(num))
  })
})
