/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettlementsRouteImport } from './routes/settlements'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaySlugRouteImport } from './routes/pay.$slug'
import { Route as CheckoutPaymentIdRouteImport } from './routes/checkout.$paymentId'

const SettlementsRoute = SettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentIdRoute = CheckoutPaymentIdRouteImport.update({
  id: '/checkout/$paymentId',
  path: '/checkout/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/settlements': typeof SettlementsRoute
  '/checkout/$paymentId': typeof CheckoutPaymentIdRoute
  '/pay/$slug': typeof PaySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/settlements': typeof SettlementsRoute
  '/checkout/$paymentId': typeof CheckoutPaymentIdRoute
  '/pay/$slug': typeof PaySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/settlements': typeof SettlementsRoute
  '/checkout/$paymentId': typeof CheckoutPaymentIdRoute
  '/pay/$slug': typeof PaySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payments'
    | '/settings'
    | '/settlements'
    | '/checkout/$paymentId'
    | '/pay/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/payments'
    | '/settings'
    | '/settlements'
    | '/checkout/$paymentId'
    | '/pay/$slug'
  id:
    | '__root__'
    | '/'
    | '/payments'
    | '/settings'
    | '/settlements'
    | '/checkout/$paymentId'
    | '/pay/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaymentsRoute: typeof PaymentsRoute
  SettingsRoute: typeof SettingsRoute
  SettlementsRoute: typeof SettlementsRoute
  CheckoutPaymentIdRoute: typeof CheckoutPaymentIdRoute
  PaySlugRoute: typeof PaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settlements': {
      id: '/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof SettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$slug': {
      id: '/pay/$slug'
      path: '/pay/$slug'
      fullPath: '/pay/$slug'
      preLoaderRoute: typeof PaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$paymentId': {
      id: '/checkout/$paymentId'
      path: '/checkout/$paymentId'
      fullPath: '/checkout/$paymentId'
      preLoaderRoute: typeof CheckoutPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaymentsRoute: PaymentsRoute,
  SettingsRoute: SettingsRoute,
  SettlementsRoute: SettlementsRoute,
  CheckoutPaymentIdRoute: CheckoutPaymentIdRoute,
  PaySlugRoute: PaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
