/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as PaySlugRouteImport } from './routes/pay.$slug'
import { Route as CheckoutPaymentIdRouteImport } from './routes/checkout.$paymentId'
import { Route as DashboardWithdrawalRouteImport } from './routes/_dashboard.withdrawal'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard.users'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardPaymentsRouteImport } from './routes/_dashboard.payments'
import { Route as DashboardPaymentLinksRouteImport } from './routes/_dashboard.payment-links'
import { Route as DashboardBranchesRouteImport } from './routes/_dashboard.branches'
import { Route as DashboardAuditLogRouteImport } from './routes/_dashboard.audit-log'
import { Route as DashboardActivateRouteImport } from './routes/_dashboard.activate'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentIdRoute = CheckoutPaymentIdRouteImport.update({
  id: '/checkout/$paymentId',
  path: '/checkout/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWithdrawalRoute = DashboardWithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentLinksRoute = DashboardPaymentLinksRouteImport.update({
  id: '/payment-links',
  path: '/payment-links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchesRoute = DashboardBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogRoute = DashboardAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivateRoute = DashboardActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/activate': typeof DashboardActivateRoute
  '/audit-log': typeof DashboardAuditLogRoute
  '/branches': typeof DashboardBranchesRoute
  '/payment-links': typeof DashboardPaymentLinksRoute
  '/payments': typeof DashboardPaymentsRoute
  '/settings': typeof DashboardSettingsRoute
  '/users': typeof DashboardUsersRoute
  '/withdrawal': typeof DashboardWithdrawalRoute
  '/checkout/$paymentId': typeof CheckoutPaymentIdRoute
  '/pay/$slug': typeof PaySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/activate': typeof DashboardActivateRoute
  '/audit-log': typeof DashboardAuditLogRoute
  '/branches': typeof DashboardBranchesRoute
  '/payment-links': typeof DashboardPaymentLinksRoute
  '/payments': typeof DashboardPaymentsRoute
  '/settings': typeof DashboardSettingsRoute
  '/users': typeof DashboardUsersRoute
  '/withdrawal': typeof DashboardWithdrawalRoute
  '/checkout/$paymentId': typeof CheckoutPaymentIdRoute
  '/pay/$slug': typeof PaySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_dashboard/activate': typeof DashboardActivateRoute
  '/_dashboard/audit-log': typeof DashboardAuditLogRoute
  '/_dashboard/branches': typeof DashboardBranchesRoute
  '/_dashboard/payment-links': typeof DashboardPaymentLinksRoute
  '/_dashboard/payments': typeof DashboardPaymentsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/withdrawal': typeof DashboardWithdrawalRoute
  '/checkout/$paymentId': typeof CheckoutPaymentIdRoute
  '/pay/$slug': typeof PaySlugRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/activate'
    | '/audit-log'
    | '/branches'
    | '/payment-links'
    | '/payments'
    | '/settings'
    | '/users'
    | '/withdrawal'
    | '/checkout/$paymentId'
    | '/pay/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/activate'
    | '/audit-log'
    | '/branches'
    | '/payment-links'
    | '/payments'
    | '/settings'
    | '/users'
    | '/withdrawal'
    | '/checkout/$paymentId'
    | '/pay/$slug'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_auth/register'
    | '/_dashboard/activate'
    | '/_dashboard/audit-log'
    | '/_dashboard/branches'
    | '/_dashboard/payment-links'
    | '/_dashboard/payments'
    | '/_dashboard/settings'
    | '/_dashboard/users'
    | '/_dashboard/withdrawal'
    | '/checkout/$paymentId'
    | '/pay/$slug'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  CheckoutPaymentIdRoute: typeof CheckoutPaymentIdRoute
  PaySlugRoute: typeof PaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/pay/$slug': {
      id: '/pay/$slug'
      path: '/pay/$slug'
      fullPath: '/pay/$slug'
      preLoaderRoute: typeof PaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$paymentId': {
      id: '/checkout/$paymentId'
      path: '/checkout/$paymentId'
      fullPath: '/checkout/$paymentId'
      preLoaderRoute: typeof CheckoutPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/withdrawal': {
      id: '/_dashboard/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof DashboardWithdrawalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/payments': {
      id: '/_dashboard/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/payment-links': {
      id: '/_dashboard/payment-links'
      path: '/payment-links'
      fullPath: '/payment-links'
      preLoaderRoute: typeof DashboardPaymentLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/branches': {
      id: '/_dashboard/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof DashboardBranchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/audit-log': {
      id: '/_dashboard/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof DashboardAuditLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/activate': {
      id: '/_dashboard/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof DashboardActivateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardActivateRoute: typeof DashboardActivateRoute
  DashboardAuditLogRoute: typeof DashboardAuditLogRoute
  DashboardBranchesRoute: typeof DashboardBranchesRoute
  DashboardPaymentLinksRoute: typeof DashboardPaymentLinksRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWithdrawalRoute: typeof DashboardWithdrawalRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivateRoute: DashboardActivateRoute,
  DashboardAuditLogRoute: DashboardAuditLogRoute,
  DashboardBranchesRoute: DashboardBranchesRoute,
  DashboardPaymentLinksRoute: DashboardPaymentLinksRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWithdrawalRoute: DashboardWithdrawalRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  CheckoutPaymentIdRoute: CheckoutPaymentIdRoute,
  PaySlugRoute: PaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
